# Git ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹è¡¨ç¤ºã®è¨­å®š
[git_status]
style = '#89a0fa'
format = '$all_status$ahead_behind '
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'ğŸ™†â€â™‚ï¸'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_branch]
style = '#89a0fa'
truncation_symbol = ''
format = 'on [$branch(:$remote_branch)]($style) '

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªè¡¨ç¤ºã®è¨­å®š
[directory]
style = '#5bebaf'

# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®ã‚³ãƒãƒ³ãƒ‰å…¥åŠ›æ¬„ã®è¨­å®š
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
